CREATE OR REPLACE DATABASE SUPPLY_CHAIN_DB;

CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.RAW;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.TRANSFORMED;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.MART;
use database SUPPLY_CHAIN_DB;
use schema RAW;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  empTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  ENCODING = 'windows-1252';


CREATE OR REPLACE STAGE S3_STAGE_ORDERS
  URL = 's3://supply-chain-analytics-bk/raw/orders/'
  STORAGE_INTEGRATION = S3_role_integration
  FILE_FORMAT = CSV_FORMAT;

LIST @S3_STAGE_ORDERS;

SELECT *
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@S3_STAGE_ORDERS',
    FILE_FORMAT => 'CSV_FORMAT'
  )
);

CREATE OR REPLACE TABLE RAW.ORDERS
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@S3_STAGE_ORDERS/',
      FILE_FORMAT => 'CSV_FORMAT'
    )
  )
);


COPY INTO RAW.ORDERS
FROM @S3_STAGE_ORDERS
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
ON_ERROR = 'CONTINUE';

SELECT * FROM SUPPLY_CHAIN_DB.RAW.ORDERS limit 10;

CREATE OR REPLACE TABLE TRANSFORMED.STG_ORDERS AS
SELECT
    "c1" AS TYPE,
    "c2" AS DAYS_FOR_SHIPPING_REAL,
    "c3" AS DAYS_FOR_SHIPMENT_SCHEDULED,
    "c4" AS BENEFIT_PER_ORDER,
    "c5" AS SALES_PER_CUSTOMER,
    "c6" AS DELIVERY_STATUS,
    "c7" AS LATE_DELIVERY_RISK,
    TRIM("c8") AS CATEGORY_ID,
    TRIM("c9") AS CATEGORY_NAME,
    TRIM("c10") AS CUSTOMER_CITY,
    TRIM("c11") AS CUSTOMER_COUNTRY,
    TRIM("c12") AS CUSTOMER_EMAIL,
    TRIM("c13") AS CUSTOMER_FNAME,
    TRIM("c14") AS CUSTOMER_ID,
    TRIM("c15") AS CUSTOMER_LNAME,
    TRIM("c16") AS CUSTOMER_PASSWORD,
    TRIM("c17") AS CUSTOMER_SEGMENT,
    TRIM("c18") AS CUSTOMER_STATE,
    TRIM("c19") AS CUSTOMER_STREET,
    TRIM("c20") AS CUSTOMER_ZIPCODE,
    TRIM("c21") AS DEPARTMENT_ID,
    TRIM("c22") AS DEPARTMENT_NAME,
    "c23" AS LATITUDE,
    "c24" AS LONGITUDE,
    TRIM("c25") AS MARKET,
    TRIM("c26") AS ORDER_CITY,
    TRIM("c27") AS ORDER_COUNTRY,
    "c28" AS ORDER_CUSTOMER_ID,
    TRY_TO_TIMESTAMP(TRIM("c29"), 'MM/DD/YYYY HH24:MI') AS ORDER_DATE,
    TRIM("c30") AS ORDER_ID,
    "c31" AS ORDER_ITEM_CARDPROD_ID,
    "c32" AS ORDER_ITEM_DISCOUNT,
    "c33" AS ORDER_ITEM_DISCOUNT_RATE,
    TRIM("c34") AS ORDER_ITEM_ID,
    TRIM("c35") AS ORDER_ITEM_PRODUCT_PRICE,
    TRIM("c36") AS ORDER_ITEM_PROFIT_RATIO,
    TRIM("c37") AS ORDER_ITEM_QUANTITY,
    TRIM("c38") AS SALES,
    TRIM("c39") AS ORDER_ITEM_TOTAL,
    TRIM("c40") AS ORDER_PROFIT_PER_ORDER,
    TRIM("c41") AS ORDER_REGION,
    TRIM("c42") AS ORDER_STATE,
    TRIM("c43") AS ORDER_STATUS,
    -- "c44" is a blank/junk column in the source file — real Product Card Id starts at "c45".
    -- (Confirmed: old "c45"/"c46" values matched ORDER_ITEM_CARDPROD_ID / CATEGORY_ID exactly,
    -- and "c47" — real Product Description — was being dropped entirely.)
    TRIM("c45") AS PRODUCT_CARD_ID,
    TRIM("c46") AS PRODUCT_CATEGORY_ID,
    TRIM("c47") AS PRODUCT_DESCRIPTION,
    TRIM("c48") AS PRODUCT_IMAGE,
    TRIM("c49") AS PRODUCT_NAME,
    TRIM("c50") AS PRODUCT_PRICE,
    TRIM("c51") AS PRODUCT_STATUS,
    TRY_TO_TIMESTAMP(TRIM("c52"), 'MM/DD/YYYY HH24:MI') AS SHIPPING_DATE,
    TRIM("c53") AS SHIPPING_MODE,
    DATEDIFF(day, TRY_TO_TIMESTAMP(TRIM("c29"), 'MM/DD/YYYY HH24:MI'), TRY_TO_TIMESTAMP(TRIM("c52"), 'MM/DD/YYYY HH24:MI')) AS DAYS_BETWEEN_ORDER_AND_SHIP
FROM RAW.ORDERS;

DESC TABLE RAW.ORDERS; 
DESC TABLE TRANSFORMED.STG_ORDERS;
SELECT
    COUNT_IF(ORDER_DATE IS NULL) AS NULL_ORDER_DATE,
    COUNT_IF(SHIPPING_DATE IS NULL) AS NULL_SHIPPING_DATE,
    COUNT_IF(DAYS_BETWEEN_ORDER_AND_SHIP IS NULL) AS NULL_DAYS_BETWEEN
FROM TRANSFORMED.STG_ORDERS;

SELECT * FROM TRANSFORMED.STG_ORDERS
LIMIT 10;

-- Customers with more than one distinct street on file: customer attributes are not
-- strictly 1:1 with CUSTOMER_ID, so DIM_CUSTOMER below picks the address from the
-- customer's most recent order rather than an arbitrary row.
SELECT CUSTOMER_ID, COUNT(DISTINCT CUSTOMER_STREET) AS ADDRESS_COUNT
FROM TRANSFORMED.STG_ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT CUSTOMER_STREET) > 1;

-- ============================================================================
-- STAR SCHEMA FOR TABLEAU  (grain of FACT_ORDERS = one row per ORDER_ITEM_ID)
-- ============================================================================

-- DIM_CUSTOMER: one row per customer, using the address/segment from their most
-- recent order (customers can have multiple addresses on file, see check above).
CREATE OR REPLACE TABLE MART.DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_FNAME,
    CUSTOMER_LNAME,
    CUSTOMER_EMAIL,
    CUSTOMER_SEGMENT,
    CUSTOMER_STREET,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_ZIPCODE,
    CUSTOMER_COUNTRY
FROM (
    SELECT
        CUSTOMER_ID, CUSTOMER_FNAME, CUSTOMER_LNAME, CUSTOMER_EMAIL, CUSTOMER_SEGMENT,
        CUSTOMER_STREET, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_ZIPCODE, CUSTOMER_COUNTRY,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS RN
    FROM TRANSFORMED.STG_ORDERS
)
WHERE RN = 1;

-- DIM_PRODUCT: one row per product (PRODUCT_CARD_ID, now fixed above), latest
-- known attributes (catalog price/name are effectively static in this dataset).
CREATE OR REPLACE TABLE MART.DIM_PRODUCT AS
SELECT
    PRODUCT_CARD_ID,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_IMAGE,
    CATEGORY_ID,
    CATEGORY_NAME,
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM (
    SELECT
        PRODUCT_CARD_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_IMAGE,
        CATEGORY_ID, CATEGORY_NAME, DEPARTMENT_ID, DEPARTMENT_NAME,
        ROW_NUMBER() OVER (PARTITION BY PRODUCT_CARD_ID ORDER BY ORDER_DATE DESC) AS RN
    FROM TRANSFORMED.STG_ORDERS
    WHERE PRODUCT_CARD_ID IS NOT NULL
)
WHERE RN = 1;

-- DIM_GEOGRAPHY: distinct order destinations (market/region/country/state/city).
-- Surrogate key is a deterministic hash so it can be recomputed identically in the fact table.
CREATE OR REPLACE TABLE MART.DIM_GEOGRAPHY AS
SELECT DISTINCT
    HASH(MARKET, ORDER_REGION, ORDER_COUNTRY, ORDER_STATE, ORDER_CITY) AS GEOGRAPHY_KEY,
    MARKET,
    ORDER_REGION,
    ORDER_COUNTRY,
    ORDER_STATE,
    ORDER_CITY
FROM TRANSFORMED.STG_ORDERS;

-- DIM_DATE: calendar dimension spanning the full order/shipping date range.
-- Used as a role-playing dimension: FACT_ORDERS.ORDER_DATE_KEY and .SHIP_DATE_KEY
-- both join to DIM_DATE.DATE_DAY (create two Tableau data source connections, or
-- rename/alias the table, to use it in both roles).
CREATE OR REPLACE TABLE MART.DIM_DATE AS
WITH bounds AS (
    SELECT DATE(MIN(ORDER_DATE)) AS MIN_DATE, DATE(MAX(SHIPPING_DATE)) AS MAX_DATE
    FROM TRANSFORMED.STG_ORDERS
),
days AS (
    SELECT DATEADD(day, SEQ4(), (SELECT MIN_DATE FROM bounds)) AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 5000))
)
SELECT
    DATE_DAY,
    YEAR(DATE_DAY) AS YEAR,
    QUARTER(DATE_DAY) AS QUARTER,
    MONTH(DATE_DAY) AS MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    DAY(DATE_DAY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK,
    DAYNAME(DATE_DAY) AS DAY_NAME,
    WEEKOFYEAR(DATE_DAY) AS WEEK_OF_YEAR,
    IFF(DAYOFWEEK(DATE_DAY) IN (0, 6), TRUE, FALSE) AS IS_WEEKEND
FROM days
WHERE DATE_DAY <= (SELECT MAX_DATE FROM bounds);

-- FACT_ORDERS: one row per order item, holding measures + FKs to the dims above.
-- SHIPPING_MODE / DELIVERY_STATUS / LATE_DELIVERY_RISK / PAYMENT_TYPE / ORDER_STATUS
-- are kept as degenerate dimensions directly on the fact (low cardinality, no extra
-- attributes of their own, so a separate dim table would just add a pointless join).
CREATE OR REPLACE TABLE MART.FACT_ORDERS AS
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_CARD_ID,
    HASH(MARKET, ORDER_REGION, ORDER_COUNTRY, ORDER_STATE, ORDER_CITY) AS GEOGRAPHY_KEY,
    DATE(ORDER_DATE) AS ORDER_DATE_KEY,
    DATE(SHIPPING_DATE) AS SHIP_DATE_KEY,
    ORDER_DATE,
    SHIPPING_DATE,
    TYPE AS PAYMENT_TYPE,
    SHIPPING_MODE,
    DELIVERY_STATUS,
    LATE_DELIVERY_RISK,
    ORDER_STATUS,
    ORDER_ITEM_QUANTITY,
    ORDER_ITEM_PRODUCT_PRICE,
    ORDER_ITEM_DISCOUNT,
    ORDER_ITEM_DISCOUNT_RATE,
    SALES,
    ORDER_ITEM_TOTAL,
    ORDER_PROFIT_PER_ORDER,
    BENEFIT_PER_ORDER,
    ORDER_ITEM_PROFIT_RATIO,
    SALES_PER_CUSTOMER,
    DAYS_FOR_SHIPPING_REAL,
    DAYS_FOR_SHIPMENT_SCHEDULED,
    DAYS_BETWEEN_ORDER_AND_SHIP
FROM TRANSFORMED.STG_ORDERS;

-- QA: row counts should match STG_ORDERS grain, and every FK should resolve.
SELECT COUNT(*) AS FACT_ROWS FROM MART.FACT_ORDERS;

SELECT COUNT(*) AS ORPHAN_CUSTOMERS
FROM MART.FACT_ORDERS f
LEFT JOIN MART.DIM_CUSTOMER d ON f.CUSTOMER_ID = d.CUSTOMER_ID
WHERE d.CUSTOMER_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_PRODUCTS
FROM MART.FACT_ORDERS f
LEFT JOIN MART.DIM_PRODUCT d ON f.PRODUCT_CARD_ID = d.PRODUCT_CARD_ID
WHERE d.PRODUCT_CARD_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_GEOGRAPHY
FROM MART.FACT_ORDERS f
LEFT JOIN MART.DIM_GEOGRAPHY d ON f.GEOGRAPHY_KEY = d.GEOGRAPHY_KEY
WHERE d.GEOGRAPHY_KEY IS NULL;

SELECT COUNT(*) AS ORPHAN_ORDER_DATES
FROM MART.FACT_ORDERS f
LEFT JOIN MART.DIM_DATE d ON f.ORDER_DATE_KEY = d.DATE_DAY
WHERE d.DATE_DAY IS NULL;